### PR TITLE
Update demo + readme for Windows builds with webpack config.

### LINKED ISSUE #1: Module issues
Hi,
This project fails on Windows. Steps to reproduce:

- `npm install`
- `npm run build-demo-wp`

Produces result:
```

> webpack-alternate-require-loader@0.0.2 build-demo-wp C:\Users\GM\Documents\webpack-alternate-require-loader
> npm run clean && cd demo && webpack


> webpack-alternate-require-loader@0.0.2 clean C:\Users\GM\Documents\webpack-alternate-require-loader
> rimraf demo/build*

Hash: 13d15d66c8c7a9bf4b7b
Version: webpack 1.14.0
Time: 94ms
  Asset     Size  Chunks             Chunk Names
main.js  2.36 kB       0  [emitted]  main
   [0] ./main.js 611 bytes {0} [built] [2 errors]

ERROR in ./main.js
Module not found: Error: Cannot resolve module 'C:UsersGMDocumentswebpack-alternate-require-loaderdemo
ested
ode_modules
           ooindex.js' in C:\Users\GM\Documents\webpack-alternate-require-loader\demo
 @ ./main.js 13:10-129

ERROR in ./main.js
Module not found: Error: Cannot resolve module 'C:UsersGMDocumentswebpack-alternate-require-loaderdemar.js' in C:\Users\GM\Documents\webpack-alternate-require-loader\demo
 @ ./main.js 16:10-103
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webpack-alternate-require-loader@0.0.2 build-demo-wp: `npm run clean && cd demo && webpack`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webpack-alternate-require-loader@0.0.2 build-demo-wp script 'npm run clean && cd demo && webpack'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the webpack-alternate-require-loader package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run clean && cd demo && webpack
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs webpack-alternate-require-loader
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls webpack-alternate-require-loader
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\GM\AppData\Roaming\npm-cache\_logs\2017-04-05T07_22_11_752Z-debug.log

```

Node version: 7.8.0 32bit
Npm version: 4.4.4

### PR DESCRIPTION
**Pull request by ryan-roemer**
Fixes #1 

Alternate demo fix in place of #2

@GEMI -- can you try this out and see if it fixes the issue in #1 for you?

### CODE REVIEW

**Comment by GEMI** [comment]
Hi, unfortunately I am still getting the same error.

```
Hash: 13d15d66c8c7a9bf4b7b
Version: webpack 1.14.0
Time: 82ms
  Asset     Size  Chunks             Chunk Names
main.js  2.36 kB       0  [emitted]  main
   [0] ./main.js 611 bytes {0} [built] [2 errors]

ERROR in ./main.js
Module not found: Error: Cannot resolve module 'C:UsersGMDocumentswebpack-alternate-require-loaderdemo
ested
ode_modules
           ooindex.js' in C:\Users\GM\Documents\webpack-alternate-require-loader\demo
 @ ./main.js 13:10-129

ERROR in ./main.js
Module not found: Error: Cannot resolve module 'C:UsersGMDocumentswebpack-alternate-require-loaderdemar.js' in C:\Users\GM\Documents\webpack-alternate-require-loader\demo
 @ ./main.js 16:10-103
```

**Comment by ryan-roemer** [comment]
@GEMI -- I think it was too early and I lacked the coffee to think clearly -- it's `path.sep` that needs to be replaced, not `os.EOL`...

I've pushed my fixes to this branch. Can you try again?

**Comment by GEMI** [comment]
Hehe, you need more coffee 😄 
First of all, `.replace()` only replaces the first occurrence inside the string. So that does not work.
Secondly, I have tested to add the replacement part in both webpack config and in lib/index.js. 

- Adding this replacement code to webpack config does not do anything. 

- When I replace inside the lib/index.js it works fine. I am not sure why but apparently the require that is done inside lib/index.js behaves differently than the one inside webpack config. 

So what actually works for me is this:

```
    var resolved = resolver.resolve(modPath).split(path.sep).join("/");

    // Mutate.
    return "require(\"" + resolved + "\")";
```

What I have observed in the code is that the resolved path is always with single backslash.
E.g. var resolved = resolver.resolve(modPath); // `C:\Users\GM\Documents\webpack-alternate-require-loader\demo\nested\node_modules\foo\index.js`
This does not work when we provide it to the require here: return "require(\"" + resolved + "\")";

However, after replacing backslash with regular slash:
E.g. var resolved = resolver.resolve(modPath); // `C:/Users/GM/Documents/webpack-alternate-require-loader/demo/nested/node_modules/foo/index.js`
When this string is provided to the require it works fine.

**Comment by ryan-roemer** [comment]
:man_facepalming: 

So... I finally did what I should have before and actually pulled a Windows VM and tried this stuff out.

The webpack resolver thing is just where to find the nested package's `module.export = require` file, not the actual resolved path spit out by the loader. The latter is what's actually going wrong.

Closing this in favor of your PR.

**Pull request closed without merging**
